runtime: python311
entrypoint: gunicorn -b :$PORT myproject.wsgi

env_variables:
  DJANGO_SETTINGS_MODULE: myproject.settings

handlers:
- url: /static
  static_dir: static/
- url: /.*
  script: auto

